# Generated by Django 5.1.6 on 2025-02-19 02:14

from django.core.management import call_command
from django.db import migrations


def load_fixtures(apps, schema_editor):
    call_command("loaddata", "-v", "0", "initial_data")

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    editor_group = Group.objects.get(name="Editor")
    editor_group.permissions.set(
        Permission.objects.filter(
            codename__contains="newspost", content_type__app_label="news"
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("plan", "0002_plan_name"),
    ]

    operations = [
        migrations.RunPython(load_fixtures, lambda apps, schema_editor: None),
    ]
