# Generated by Django 5.1.6 on 2025-02-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="name",
            field=models.CharField(default="Jota", max_length=255),
            preserve_default=False,
        ),
    ]
